// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Sy8s1X3BV7DgvFvtoy9lbsrWBcX6-G4',
    appId: '1:904023712340:android:afc81344f6b883198cc3c1',
    messagingSenderId: '904023712340',
    projectId: 'social-app-395ca',
    storageBucket: 'social-app-395ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1pP2KzkKCKiBVz_AHOwdSQXT9ubzcHPc',
    appId: '1:904023712340:ios:43060386b0b1421f8cc3c1',
    messagingSenderId: '904023712340',
    projectId: 'social-app-395ca',
    storageBucket: 'social-app-395ca.appspot.com',
    iosClientId: '904023712340-oer1vsg8kivhr5v16ncldefl4oui0gu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.social',
  );
}
